"""initial schema -- full SkillSwap domain model

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-06

Hand-written (not autogenerated) to match app/models/*.py exactly. Tables
are created in FK-dependency order; downgrade tears down in reverse and
explicitly drops the Postgres ENUM types Alembic/SQLAlchemy create
implicitly on first use (op.drop_table alone does not drop them).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- users ---
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column("password_hash", sa.String(255), nullable=True),
        sa.Column("google_id", sa.String(64), nullable=True),
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column("photo_url", sa.String(512), nullable=True),
        sa.Column("timezone", sa.String(64), nullable=False, server_default="UTC"),
        sa.Column("is_email_verified", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("is_admin", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("totp_secret", sa.String(64), nullable=True),
        sa.Column("totp_enabled", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_index("ix_users_google_id", "users", ["google_id"], unique=True)

    # --- login_audits ---
    op.create_table(
        "login_audits",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("email_attempted", sa.String(255), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("ip_address", sa.String(64), nullable=False),
        sa.Column("user_agent", sa.String(512), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_login_audits_user_id", "login_audits", ["user_id"])

    # --- skills ---
    op.create_table(
        "skills",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("category", sa.String(60), nullable=False),
    )
    op.create_index("ix_skills_name", "skills", ["name"], unique=True)
    op.create_index("ix_skills_category", "skills", ["category"])

    # --- user_skills ---
    skill_type_enum = sa.Enum("have", "want", name="skill_type")
    op.create_table(
        "user_skills",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("skill_id", sa.Integer(), sa.ForeignKey("skills.id", ondelete="CASCADE"), nullable=False),
        sa.Column("type", skill_type_enum, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.UniqueConstraint("user_id", "skill_id", "type", name="uq_user_skill_type"),
    )
    op.create_index("ix_user_skills_user_id", "user_skills", ["user_id"])
    op.create_index("ix_user_skills_skill_id", "user_skills", ["skill_id"])

    # --- availability_blocks ---
    op.create_table(
        "availability_blocks",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("day_of_week", sa.SmallInteger(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("timezone", sa.String(64), nullable=False),
    )
    op.create_index("ix_availability_blocks_user_id", "availability_blocks", ["user_id"])

    # --- swap_requests ---
    swap_status_enum = sa.Enum("pending", "accepted", "declined", name="swap_request_status")
    op.create_table(
        "swap_requests",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("requester_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("recipient_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("skill_taught_id", sa.Integer(), sa.ForeignKey("skills.id"), nullable=False),
        sa.Column("skill_learned_id", sa.Integer(), sa.ForeignKey("skills.id"), nullable=False),
        sa.Column("status", swap_status_enum, nullable=False, server_default="pending"),
        sa.Column("proposed_start_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("proposed_end_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_swap_requests_requester_id", "swap_requests", ["requester_id"])
    op.create_index("ix_swap_requests_recipient_id", "swap_requests", ["recipient_id"])

    # --- sessions ---
    session_status_enum = sa.Enum(
        "scheduled", "in_progress", "completed", "cancelled", "no_show", name="session_status"
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("request_id", sa.Integer(), sa.ForeignKey("swap_requests.id"), nullable=True),
        sa.Column("scheduled_start_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scheduled_end_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", session_status_enum, nullable=False, server_default="scheduled"),
        sa.Column("video_room_id", sa.String(64), nullable=False),
        sa.Column("is_group", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("max_participants", sa.Integer(), nullable=False, server_default="2"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_sessions_video_room_id", "sessions", ["video_room_id"], unique=True)

    # --- session_participants ---
    participant_role_enum = sa.Enum("teacher", "learner", "guest", name="participant_role")
    op.create_table(
        "session_participants",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("session_id", sa.Integer(), sa.ForeignKey("sessions.id", ondelete="CASCADE"), nullable=False),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("role", participant_role_enum, nullable=False),
    )
    op.create_index("ix_session_participants_session_id", "session_participants", ["session_id"])
    op.create_index("ix_session_participants_user_id", "session_participants", ["user_id"])

    # --- conversations ---
    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    # --- conversation_participants ---
    op.create_table(
        "conversation_participants",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("conversation_id", sa.Integer(), sa.ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
    )
    op.create_index("ix_conversation_participants_conversation_id", "conversation_participants", ["conversation_id"])
    op.create_index("ix_conversation_participants_user_id", "conversation_participants", ["user_id"])

    # --- messages ---
    message_type_enum = sa.Enum("text", "voice", name="message_type")
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("conversation_id", sa.Integer(), sa.ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False),
        sa.Column("sender_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("type", message_type_enum, nullable=False, server_default="text"),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("content_url", sa.String(512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_messages_conversation_id", "messages", ["conversation_id"])
    op.create_index("ix_messages_created_at", "messages", ["created_at"])

    # --- credit_transactions ---
    credit_type_enum = sa.Enum("earned", "spent", "refunded", name="credit_type")
    credit_status_enum = sa.Enum("pending", "available", "spent", "refunded", name="credit_status")
    op.create_table(
        "credit_transactions",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("type", credit_type_enum, nullable=False),
        sa.Column("session_id", sa.Integer(), sa.ForeignKey("sessions.id"), nullable=True),
        sa.Column("status", credit_status_enum, nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.CheckConstraint("amount IN (1, -1)", name="ck_credit_amount_unit"),
    )
    op.create_index("ix_credit_transactions_user_id", "credit_transactions", ["user_id"])
    op.create_index("ix_credit_transactions_session_id", "credit_transactions", ["session_id"])
    op.create_index("ix_credit_transactions_status", "credit_transactions", ["status"])
    op.create_index("ix_credit_transactions_available_at", "credit_transactions", ["available_at"])

    # --- ratings ---
    op.create_table(
        "ratings",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("session_id", sa.Integer(), sa.ForeignKey("sessions.id", ondelete="CASCADE"), nullable=False),
        sa.Column("rater_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("ratee_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("score", sa.SmallInteger(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.CheckConstraint("score >= 1 AND score <= 5", name="ck_rating_score_range"),
        sa.UniqueConstraint("session_id", "rater_id", "ratee_id", name="uq_rating_once_per_session_pair"),
    )
    op.create_index("ix_ratings_session_id", "ratings", ["session_id"])
    op.create_index("ix_ratings_ratee_id", "ratings", ["ratee_id"])

    # --- refresh_tokens ---
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("token_hash", sa.String(128), nullable=False),
        sa.Column("replaces_id", sa.Integer(), sa.ForeignKey("refresh_tokens.id"), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_refresh_tokens_user_id", "refresh_tokens", ["user_id"])
    op.create_index("ix_refresh_tokens_token_hash", "refresh_tokens", ["token_hash"], unique=True)

    # --- otp_codes ---
    otp_purpose_enum = sa.Enum("signup_verify", "password_reset", "2fa", name="otp_purpose")
    op.create_table(
        "otp_codes",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("code_hash", sa.String(128), nullable=False),
        sa.Column("purpose", otp_purpose_enum, nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_otp_codes_user_id", "otp_codes", ["user_id"])


def downgrade() -> None:
    op.drop_table("otp_codes")
    op.drop_table("refresh_tokens")
    op.drop_table("ratings")
    op.drop_table("credit_transactions")
    op.drop_table("messages")
    op.drop_table("conversation_participants")
    op.drop_table("conversations")
    op.drop_table("session_participants")
    op.drop_table("sessions")
    op.drop_table("swap_requests")
    op.drop_table("availability_blocks")
    op.drop_table("user_skills")
    op.drop_table("skills")
    op.drop_table("login_audits")
    op.drop_table("users")

    bind = op.get_bind()
    for enum_name in (
        "otp_purpose",
        "credit_status",
        "credit_type",
        "message_type",
        "participant_role",
        "session_status",
        "swap_request_status",
        "skill_type",
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
